=== alternetsoft/alternet-studio-examples/Resources/Editor/QuickStarts/Parsers/XML/SimpleSchema/terminformat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.hg-online.de/terminformat" xmlns:tf="http://www.hg-online.de/terminformat" elementFormDefault="qualified">

<element name="formatierung" type="tf:formatierung" />


<complexType name="formatierung">
	<sequence>
		<element name="formate" type="tf:formate" />
	</sequence>
</complexType>


<complexType name="formate">
	<sequence>
		<element name="format" type="tf:format" minOccurs="0" maxOccurs="unbounded"/>
	</sequence>
</complexType>

<complexType name="format">
	<sequence>
		<element name="zeilen" type="tf:zeilen" />
	</sequence>
	<attribute name="terminartids" type="string"/>
	<attribute name="terminartgruppeids" type="string"/>
	<attribute name="raumids" type="string"/>
	<attribute name="ortids" type="string"/>
	<attribute name="bezirkids" type="string"/>
	<attribute name="abgesagt" type="boolean"/>
	<attribute name="vorstellung" type="boolean"/>
	<attribute name="probe" type="boolean"/>
</complexType>


<complexType name="zeilen">
	<sequence>
		<element name="zeile" type="tf:zeile" minOccurs="0" maxOccurs="unbounded"/>
	</sequence>
</complexType>

<complexType name="zeile">
	<sequence>
		<element name="spalten" type="tf:spalten" />
	</sequence>
</complexType>


<complexType name="spalten">
	<sequence>
		<element name="spalte" type="tf:spalte" minOccurs="0" maxOccurs="unbounded"/>
	</sequence>
</complexType>

<complexType name="spalte">
	<sequence>
		<element name="felder" type="tf:felder" />
	</sequence>
	<attribute name="colortype" type="tf:TerminCellColorType"/>
	<attribute name="colorrgb" type="string"/>
	<attribute name="width" type="integer"/>
	<attribute name="header" type="string"/>
	<attribute name="headerstyle" type="string"/>
	<attribute name="headercoumnspan" type="integer"/>
	<attribute name="columnspan" type="integer"/>
</complexType>


<simpleType name="TerminCellColorType">
	<restriction base="string">
		<enumeration value="KeineEinfaerbung"/> 
		<enumeration value="Terminart"/> 
		<enumeration value="Raum"/> 
		<enumeration value="Produktion"/> 
		<enumeration value="Terminstatus"/> 
		<enumeration value="RGB"/> 
	</restriction>
</simpleType>


<complexType name="felder">
	<sequence>
		<element name="feld" type="tf:feld" minOccurs="0" maxOccurs="unbounded"/>
	</sequence>
</complexType>

<complexType name="feld">
	<sequence>
	</sequence>
	<attribute name="otherfeld" type="string"/>
	<attribute name="formattermindatum" type="tf:FormatDatum"/>
	<attribute name="formatterminuhrzeit" type="tf:FormatUhrzeit"/>
	<attribute name="besetzungeninzeitabschnittenausgeben" type="string"/>
	<attribute name="formatabonnement" type="tf:TerminFormatAbonnement"/>
	<attribute name="showortbeiraumauswaerts" type="boolean"/>
	<attribute name="trennerortraum" type="string"/>
	<attribute name="formatterminart" type="string"/>
	<attribute name="formattermin" type="tf:TerminausgabeEnum"/>
	<attribute name="besetzungsausgabe_nurpublizierte" type="string"/>
	<attribute name="besetzungsausgabe_zeiten" type="boolean"/>
	<attribute name="kollektivausgabeeinteilungszustand" type="string"/>
	<attribute name="kollektivausgabe_nurpublizierte" type="boolean"/>
	<attribute name="formatkollektiv" type="string"/>
	<attribute name="besetzungsfunktionIds" type="string"/>
	<attribute name="besetzungsgruppeIds" type="string"/>
	<attribute name="formatraum" type="tf:RaumausgabeEnum"/>
	<attribute name="formatnamensausgabe" type="string"/>
	<attribute name="scriptplatzhalter" type="string"/>
	<attribute name="ausgabewert" type="boolean"/>
	<attribute name="ausgabeperson" type="boolean"/>
	<attribute name="platzhalter" type="string"/>
	<attribute name="separator" type="string"/>
	<attribute name="felddefinitionid" type="integer"/>
	<attribute name="besetzungsausgabe_rollebezeichnung" type="boolean"/>
	<attribute name="besetzungsausgabe_trennerrollebesetzung" type="string"/>
	<attribute name="besetzungsausgabe_nuraktive" type="boolean"/>
	<attribute name="besetzungsausgabe_nurbesetzte" type="boolean"/>
	<attribute name="besetzungsausgabe_bemerkung" type="boolean"/>
	<attribute name="besetzungsausgabe_sortierungrolle" type="tf:RolleSortierung"/>
	<attribute name="besetzungsausgabe_sortierungbesetzung" type="tf:BesetzungSortierung"/>
	<attribute name="feld" type="tf:TerminFeld"/>
	<attribute name="uppercase" type="boolean"/>
	<attribute name="separatorbefore" type="string"/>
	<attribute name="textbefore" type="string"/>
	<attribute name="textafter" type="string"/>
	<attribute name="lineBreakType" type="tf:LineBreakType"/>
	<attribute name="lineBreakTypeBefore" type="tf:LineBreakType"/>
	<attribute name="emptyReplacement" type="string"/>
	<attribute name="formatdatum" type="string"/>
	<attribute name="trennerliste" type="string"/>
	<attribute name="style" type="string"/>
	<attribute name="fontname" type="string"/>
	<attribute name="fontsize" type="double"/>
	<attribute name="fontbold" type="boolean"/>
	<attribute name="fontitalic" type="boolean"/>
	<attribute name="fontunderlinetype" type="tf:FontUnderlineTypeRPT"/>
	<attribute name="tabwidth" type="integer"/>
	<attribute name="tabalignment" type="tf:TabAlignment"/>
	<attribute name="feldname" type="string"/>
	<attribute name="repeatSame" type="boolean"/>
</complexType>


<simpleType name="TabAlignment">
	<restriction base="string">
		<enumeration value="Left"/> 
		<enumeration value="Center"/> 
		<enumeration value="Right"/> 
		<enumeration value="Decimal"/> 
		<enumeration value="Bar"/> 
		<enumeration value="List"/> 
		<enumeration value="Clear"/> 
	</restriction>
</simpleType>


<simpleType name="FontUnderlineTypeRPT">
	<restriction base="string">
		<enumeration value="None"/> 
		<enumeration value="Single"/> 
		<enumeration value="Double"/> 
		<enumeration value="Thick"/> 
	</restriction>
</simpleType>


<simpleType name="LineBreakType">
	<restriction base="string">
		<enumeration value="None"/> 
		<enumeration value="Always"/> 
		<enumeration value="IfNotEmpty"/> 
	</restriction>
</simpleType>


<simpleType name="TerminFeld">
	<restriction base="string">
		<enumeration value="Leer"/> 
		<enumeration value="Other"/> 
		<enumeration value="Von"/> 
		<enumeration value="Bis"/> 
		<enumeration value="VonBis"/> 
		<enumeration value="VonBisPub"/> 
		<enumeration value="VonPub"/> 
		<enumeration value="Raum"/> 
		<enumeration value="Terminart"/> 
		<enumeration value="Terminstatus"/> 
		<enumeration value="Produktionskurzbezeichnung"/> 
		<enumeration value="Terminbezeichnung"/> 
		<enumeration value="TerminUntertitel"/> 
		<enumeration value="SzenDienst"/> 
		<enumeration value="Kollektiv"/> 
		<enumeration value="TagesplanBemerkung"/> 
		<enumeration value="DispobemerkungExtern"/> 
		<enumeration value="DispobemerkungIntern"/> 
		<enumeration value="Abonnements"/> 
		<enumeration value="Verkaufsinformation"/> 
		<enumeration value="Kuenstler"/> 
		<enumeration value="Ablauf"/> 
		<enumeration value="ProbenZeitabschnitte"/> 
		<enumeration value="Produktion"/> 
		<enumeration value="Vorstellungsnummer"/> 
		<enumeration value="Verkaufseinschraenkungen"/> 
		<enumeration value="Platzhalter"/> 
		<enumeration value="Checkliste"/> 
		<enumeration value="Uebertitel"/> 
		<enumeration value="Autoren"/> 
		<enumeration value="LeadingTeam"/> 
		<enumeration value="Zusatz1"/> 
		<enumeration value="TerminDatum"/> 
		<enumeration value="KalenderFeiertag"/> 
		<enumeration value="KalenderSonstigertag"/> 
		<enumeration value="KalenderFerientag"/> 
		<enumeration value="TerminNummer"/> 
		<enumeration value="Newline"/> 
		<enumeration value="Tab"/> 
		<enumeration value="DynamischesFeld"/> 
		<enumeration value="Bild"/> 
	</restriction>
</simpleType>


<simpleType name="BesetzungSortierung">
	<restriction base="string">
		<enumeration value="Default"/> 
		<enumeration value="Nachname"/> 
	</restriction>
</simpleType>


<simpleType name="RolleSortierung">
	<restriction base="string">
		<enumeration value="Sort"/> 
		<enumeration value="OrderProbenplan"/> 
	</restriction>
</simpleType>


<simpleType name="RaumausgabeEnum">
	<restriction base="string">
		<enumeration value="Bezeichnung"/> 
		<enumeration value="DispoansichtBezeichnung"/> 
		<enumeration value="Kuerzel"/> 
		<enumeration value="Veroeffentlichungsbezeichnung"/> 
	</restriction>
</simpleType>


<simpleType name="TerminausgabeEnum">
	<restriction base="string">
		<enumeration value="Bezeichnung"/> 
		<enumeration value="Produktionskurzbezeichnung"/> 
		<enumeration value="ProduktionsAlternative"/> 
		<enumeration value="Pressetitel"/> 
	</restriction>
</simpleType>


<simpleType name="TerminFormatAbonnement">
	<restriction base="string">
		<enumeration value="Bezeichnung"/> 
		<enumeration value="Kuerzel"/> 
	</restriction>
</simpleType>


<simpleType name="FormatUhrzeit">
	<restriction base="string">
		<enumeration value="Standard"/> 
		<enumeration value="StandardKurzStundenMinuten"/> 
		<enumeration value="Voll"/> 
		<enumeration value="VollKurzStundenMinuten"/> 
	</restriction>
</simpleType>


<simpleType name="FormatDatum">
	<restriction base="string">
		<enumeration value="None"/> 
		<enumeration value="Standard"/> 
		<enumeration value="TagMonat"/> 
	</restriction>
</simpleType>

</schema>

=== alternetsoft/alternet-studio-examples/Resources/Editor/QuickStarts/Parsers/XML/SimpleSchema/sample_XMLNS.xml
<?xml version="1.0" encoding="utf-8" ?>
<formatierung xmlns="http://www.hg-online.de/terminformat" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
              xsi:schemaLocation="http://www.hg-online.de/terminformat terminformat.xsd">
  <formate>
    <format>
      <zeilen>
        <zeile>
          <spalten>
            <spalte width="40">
              <felder>
                <feld feld="VonBis" style="Vorstellung Zeile 1"/>
                <feld feld="Produktionskurzbezeichnung" textbefore=" " style="Vorstellung Zeile 1"/>
              </felder>
            </spalte>
            <spalte width="40">
              <felder>
                <feld feld="TagesplanBemerkung" style="Vorstellung Zeile 2"/>
                <!--Funktion "Direktionsdienst"-->
                <feld feld="SzenDienst" textbefore="D.: " besetzungsfunktionIds="12503"/>
              </felder>
            </spalte>
            <spalte width="40">
              <felder>
                <feld feld="Platzhalter" scriptplatzhalter="wolletest"/>

              </felder>
            </spalte>
          </spalten>
        </zeile>
      </zeilen>
    </format>
  </formate>
</formatierung>
